config/routes.rb
Rails.application.routes.draw do
    namespace :admin do
      resources :banners
    end
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  def self.find_by_group(group_name)
    self.find(:all, :conditions => ["group_name = ?", group_name])
  end
end

app/models/banner_group_name.rb
module BannerGroupName
  Names=[:home_center, :home_left, :home_right, :sidebar_right, :sidebar_right_middle, :menu_bottom]
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < Admin::ResourceController
 
end

app/helpers/banners_helper.rb
module BannersHelper
  def banners(group_name)
    Banner.find_by_group(group_name)
  end

end

app/views/admin/banners/_banners_tab.html.erb
<li<%== ' class="active"' if !defined?(current).nil? and current == "Related Products" %>>
  <%= link_to t("banners"), root_path() %>
</li>

app/views/admin/banners/_form.html.erb
<%= form_for([:admin, @banner] , :html => { :multipart => true }) do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <% if @banner.image.exists? %>
      <%= image_tag @banner.image.url(:thumb) %><br />
    <% end %>
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :target_url %><br />
    <%= f.text_field :target_link %>
  </div>
  <div class="field">
    <%= f.label :group_name %><br />
    <%= f.select :group_name, options_for_select(BannerGroupName::Names.map{|i| [i,i]}) %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/banners/edit.html.erb
<h1>Editing banner</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @banner] %> |
<%= link_to 'Back', admin_banners_path %>

app/views/admin/banners/index.html.erb
<h1>Listing banners</h1>

<table>
  <tr>
    <th>Image file name</th>
    <th>Image content type</th>
    <th>Image file size</th>
    <th>Url</th>
    <th>Banner group</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @banners.each do |banner| %>
  <tr>
    <td><%= image_tag banner.image.url(:thumb) %></td>
    <td><%= banner.image_content_type %></td>
    <td><%= banner.image_file_size %></td>
    <td><%= banner.target_link %></td>
    <td><%= banner.group_name %></td>
    <td><%= banner.name %></td>
    <td><%= banner.description %></td>
    <td><%= link_to 'Show', [:admin,banner] %></td>
    <td><%= link_to 'Edit', edit_admin_banner_path(banner) %></td>
    <td><%= link_to 'Destroy', [:admin,banner], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Banner', new_admin_banner_path %>

app/views/admin/banners/new.html.erb
<h1>New banner</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_banners_path %>

app/views/admin/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image file name:</b>
  <a href="<%= @banner.image.url  %>"><%= image_tag @banner.image.url(:medium) %></a>
</p>

<p>
  <b>Url:</b>
  <%= @banner.target_link %>
</p>

<p>
  <b>Banner group:</b>
  <%= @banner.group_name %>
</p>

<p>
  <b>Name:</b>
  <%= @banner.name %>
</p>

<p>
  <b>Description:</b>
  <%= @banner.description %>
</p>


<%= link_to 'Edit', edit_admin_banner_path(@banner) %> |
<%= link_to 'Back', admin_banners_path %>

app/views/banners/_all.html.erb
<% if banners.any? %>
  <% banners.each do |banner| %>
    <%= image_tag banner.image.url, :alt => banner.description, :class=>:banner %>
  <% end %>
<% end %>